from stable_baselines3 import DQN
from env.env import PlaneGliderEnv

env = PlaneGliderEnv()

#verbose means the quality of the output generated by the program
model = DQN("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=50000)

model.save('../models/plane_dqn_model')
print("Model saved as plane_dqn_model.zip")